FROM ghcr.io/mlflow/mlflow:v2.9.2

# MySQL 드라이버 및 필요한 패키지 설치
RUN pip install --no-cache-dir psycopg2-binary

ENV MLFLOW_BACKEND_STORE_URI=""
ENV MLFLOW_ARTIFACT_ROOT=""

# MLflow 실행
CMD mlflow server --host 0.0.0.0 --port 5000 \
    --backend-store-uri $MLFLOW_BACKEND_STORE_URI \
    --default-artifact-root $MLFLOW_ARTIFACT_ROOT \
    --gunicorn-opts "--log-level debug"
