version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"  # S3 API 포트
      - "9001:9001"  # 웹 콘솔 포트
    environment:
      MINIO_ROOT_USER: 'nolly'
      MINIO_ROOT_PASSWORD: 'nolly1234'
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  minio-data:
